package com.sample.rules
 
import com.sample.Klima;

 
rule "Snaga 50 kvadrata i manje  i jedna prostorija"
    when 
    	k: Klima(velicinaStana<=50,brojProstorija=="jedna",snaga==0)
    then
    	k.setSnaga(9000);
    	update(k);
end

rule "Snaga 50 kvadrata i manje  i vise prostorija"
    when 
    	k: Klima(velicinaStana<=50,brojProstorija=="vise",snaga==0)
    then
    	k.setSnaga(12000);
    	update(k);
end

rule "Snaga izmedju 50 i 75  i jedna prostorija"
    when 
    	k: Klima(velicinaStana>50,velicinaStana<=75,brojProstorija=="jedna",snaga==0)
    then
    	k.setSnaga(12000);
    	update(k);
end

rule "Snaga izmedju 50 i 75  i vise prostorija"
    when 
    	k: Klima(velicinaStana>50,velicinaStana<=75,brojProstorija=="vise",snaga==0)
    then
    	k.setSnaga(18000);
    	update(k);
end

rule "Snaga vise od 75  i bez obzira  prostorija"
    when 
    	k: Klima(velicinaStana>75,snaga==0)
    then
    	k.setSnaga(18000);
    	update(k);
end

rule "Tip klime pokretna"
    when 
    	k: Klima(ugradnjaNaZid=="nije moguca",brojProstorija=="vise",tip=="zidna")
    then
    	k.setTip("pokretna");
    	update(k);
end

rule "Tip klime prozorska"
    when 
    	k: Klima(ugradnjaNaZid=="nije moguca",brojProstorija=="jedna",tip=="zidna")
    then
    	k.setTip("prozorska");
    	update(k);
end

rule "Inverter nize temp"
    when 
    	k: Klima(nizeTemperature=="postoje")
    then
    	k.setInverter("treba");
    	update(k);
end
rule "Inverter hladjenje"
    when 
    	k: Klima(koriscenje=="hladjenje")
    then
    	k.setInverter(" ne treba");
    	update(k);
end

rule "Inverter hladjenje/grejanje"
    when 
    	k: Klima(koriscenje=="hladjenje/grejanje")
    then
    	k.setInverter("treba");
    	update(k);
end